language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install .
  - pip install nose simplejson Flask-SQLAlchemy Flask-MongoEngine Flask-Peewee Flask-Mail mock
  - pip install git+https://github.com/allanice001/MySQLdb1
  - pip install oauth2client google-api-python-client foursquare python-twitter
  - pip install http://github.com/pythonforfacebook/facebook-sdk/tarball/master

before_script:
  - mysql -e 'create database flask_social_test;'

services:
  - mongodb

script: nosetests

branches:
  only:
    - master
    - develop
